### ISSUE TITLE
Name uploaded files with its hash

### ISSUE THREAD

**Issue by IRHM** [graveship/Melodiy-prototype#13]
Currently uploaded files are stored with a random UUID as its file name.

If we change this so that file names are a hash of its content, we can reduce duplication by checking if a file hash exists as a file already at upload.

This can be done for uploaded music and artwork.

**Comment by graveship** [comment]
This a way better soloution for solving duplication to what i had in mind reduces processing time aswell as hashes will only be computed once.

This feature would be easier to implement after #28 is completed.

**Comment by graveship** [comment]
After reworking the file uploading to include user folders i realised it would be alot easier to implement this feature before #28

**Comment by graveship** [comment]
Completed Thank you for youre suggestion
