### ISSUE TITLE
Songs disappearing from search results

### ISSUE THREAD

**Issue by IRHM** [graveship/Melodiy-prototype#32]
In v0.3.0, if I search for a song, I get the list correctly, however, if i play one of the songs, then refresh the page, the song I played is removed from the results.

**Comment by graveship** [comment]
Thanks for reporting the bug the issue seems to be with already stored spotify songs being ignored.

**Comment by graveship** [comment]
This issue has been fixed the search algorithm is now always ordered alphabetically before a score is generated. This avoids any problems when a list of songs are all given the same score and the earliest fetched record is kept.
