### ISSUE TITLE
Shouldnt have to login after signup

### ISSUE THREAD

**Issue by IRHM** [graveship/Melodiy-prototype#38]
After signing up to Melodiy, the user shouldn't have to login with the newly created account. The registration request should give us our auth token so we can be signed in, instantly.

**Comment by graveship** [comment]
API now returns a JWT token when the user registers, client will be updated soon.

**Comment by graveship** [comment]
Thanks for the feature request it has been completed in dev branch which should be released in 1-2weeks.
