### ISSUE TITLE
Album songs `Date Created` is wrong - Could be removed

### ISSUE THREAD

**Issue by IRHM** [graveship/Melodiy-prototype#39]
The `date created` for songs in an album are showing as the time when the album songs are added into the db cache (i presume).

![image](https://github.com/DNYLA/Melodiy/assets/37304121/18af1afb-f13d-4a18-8031-8c0ff9f66b91)

I think for albums like this, we could probably just remove the whole column, since each song will just have the same date as in the playlist info above.

**Comment by graveship** [comment]
Thanks for pointing this out i thought i had removed the column for albums.

Should be fixed in the next update.
